/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lfrgs.example.service.dnd.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Character service. Represents a row in the &quot;DND_Character&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lfrgs.example.service.dnd.model.impl.CharacterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lfrgs.example.service.dnd.model.impl.CharacterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Character
 * @see com.lfrgs.example.service.dnd.model.impl.CharacterImpl
 * @see com.lfrgs.example.service.dnd.model.impl.CharacterModelImpl
 * @generated
 */
@ProviderType
public interface CharacterModel extends BaseModel<Character>, GroupedModel,
	MVCCModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a character model instance should use the {@link Character} interface instead.
	 */

	/**
	 * Returns the primary key of this character.
	 *
	 * @return the primary key of this character
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this character.
	 *
	 * @param primaryKey the primary key of this character
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this character.
	 *
	 * @return the mvcc version of this character
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this character.
	 *
	 * @param mvccVersion the mvcc version of this character
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the character ID of this character.
	 *
	 * @return the character ID of this character
	 */
	public long getCharacterId();

	/**
	 * Sets the character ID of this character.
	 *
	 * @param characterId the character ID of this character
	 */
	public void setCharacterId(long characterId);

	/**
	 * Returns the group ID of this character.
	 *
	 * @return the group ID of this character
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this character.
	 *
	 * @param groupId the group ID of this character
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this character.
	 *
	 * @return the company ID of this character
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this character.
	 *
	 * @param companyId the company ID of this character
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this character.
	 *
	 * @return the user ID of this character
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this character.
	 *
	 * @param userId the user ID of this character
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this character.
	 *
	 * @return the user uuid of this character
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this character.
	 *
	 * @param userUuid the user uuid of this character
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this character.
	 *
	 * @return the user name of this character
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this character.
	 *
	 * @param userName the user name of this character
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this character.
	 *
	 * @return the create date of this character
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this character.
	 *
	 * @param createDate the create date of this character
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this character.
	 *
	 * @return the modified date of this character
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this character.
	 *
	 * @param modifiedDate the modified date of this character
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the level of this character.
	 *
	 * @return the level of this character
	 */
	public int getLevel();

	/**
	 * Sets the level of this character.
	 *
	 * @param level the level of this character
	 */
	public void setLevel(int level);

	/**
	 * Returns the race of this character.
	 *
	 * @return the race of this character
	 */
	@AutoEscape
	public String getRace();

	/**
	 * Sets the race of this character.
	 *
	 * @param race the race of this character
	 */
	public void setRace(String race);

	/**
	 * Returns the character class of this character.
	 *
	 * @return the character class of this character
	 */
	@AutoEscape
	public String getCharacterClass();

	/**
	 * Sets the character class of this character.
	 *
	 * @param characterClass the character class of this character
	 */
	public void setCharacterClass(String characterClass);

	/**
	 * Returns the character name of this character.
	 *
	 * @return the character name of this character
	 */
	@AutoEscape
	public String getCharacterName();

	/**
	 * Sets the character name of this character.
	 *
	 * @param characterName the character name of this character
	 */
	public void setCharacterName(String characterName);

	/**
	 * Returns the strength of this character.
	 *
	 * @return the strength of this character
	 */
	public int getStrength();

	/**
	 * Sets the strength of this character.
	 *
	 * @param strength the strength of this character
	 */
	public void setStrength(int strength);

	/**
	 * Returns the dexterity of this character.
	 *
	 * @return the dexterity of this character
	 */
	public int getDexterity();

	/**
	 * Sets the dexterity of this character.
	 *
	 * @param dexterity the dexterity of this character
	 */
	public void setDexterity(int dexterity);

	/**
	 * Returns the constitution of this character.
	 *
	 * @return the constitution of this character
	 */
	public int getConstitution();

	/**
	 * Sets the constitution of this character.
	 *
	 * @param constitution the constitution of this character
	 */
	public void setConstitution(int constitution);

	/**
	 * Returns the intelligence of this character.
	 *
	 * @return the intelligence of this character
	 */
	public int getIntelligence();

	/**
	 * Sets the intelligence of this character.
	 *
	 * @param intelligence the intelligence of this character
	 */
	public void setIntelligence(int intelligence);

	/**
	 * Returns the wisdom of this character.
	 *
	 * @return the wisdom of this character
	 */
	public int getWisdom();

	/**
	 * Sets the wisdom of this character.
	 *
	 * @param wisdom the wisdom of this character
	 */
	public void setWisdom(int wisdom);

	/**
	 * Returns the charisma of this character.
	 *
	 * @return the charisma of this character
	 */
	public int getCharisma();

	/**
	 * Sets the charisma of this character.
	 *
	 * @param charisma the charisma of this character
	 */
	public void setCharisma(int charisma);

	/**
	 * Returns the speed of this character.
	 *
	 * @return the speed of this character
	 */
	public int getSpeed();

	/**
	 * Sets the speed of this character.
	 *
	 * @param speed the speed of this character
	 */
	public void setSpeed(int speed);

	/**
	 * Returns the hp of this character.
	 *
	 * @return the hp of this character
	 */
	public int getHp();

	/**
	 * Sets the hp of this character.
	 *
	 * @param hp the hp of this character
	 */
	public void setHp(int hp);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Character character);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Character> toCacheModel();

	@Override
	public Character toEscapedModel();

	@Override
	public Character toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}